version: '3.7'

services:
  monitor-db:
    image: postgres:11.5
    container_name: 'monitor-db'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=polkalert
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped
